# -*- coding: utf-8 -*-
"""internsavytask2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFr2FVwZe90EcwdbZYXQ626yzdTGy2_D
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import warnings
# %matplotlib inline
warnings.filterwarnings('ignore')

df = pd.read_csv("/content/Mall_Customers.csv")
df.head()

df.describe()

df.info()

df.isnull().sum()

df.rename(columns={'Annual Income (k$)':'Annual_Income','Spending Score (1-100)':'Spending_Score'},inplace=True)

# sns.pairplot(data=df)

X=df.iloc[:,[3,4]]
X.head()

from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=7,init="k-means++",random_state=42)
y=kmeans.fit_predict(X)
y

mall=df.copy()
mall['Claster']=y
mall.head()

sns.scatterplot(x='Annual_Income',y='Spending_Score',hue=kmeans.labels_,data=mall)

w=[]
for i in range(1,13):
    kmeans=KMeans(n_clusters=i,init="k-means++",random_state=42)
    kmeans.fit(X)
    w.append(kmeans.inertia_)
w

plt.plot(range(1,13),w)

X

mall_hierarchy=df.copy()
mall_hierarchy.head()

import scipy.cluster.hierarchy as sch
plt.figure(figsize=(20,10))
dendrogram=sch.dendrogram(sch.linkage(X,method='ward'))
plt.title("Dendrogram")
plt.xlabel("Customer")
plt.ylabel("Euclidean distances")

from sklearn.cluster import AgglomerativeClustering
clH=AgglomerativeClustering(n_clusters=7,affinity='euclidean',linkage='ward')
clH.fit(X)
AgglomerativeClustering(n_clusters=5)
yH=clH.fit_predict(X)
yH

mall_hierarchy['Claster']=yH
mall_hierarchy.head()

sns.scatterplot(x='Annual_Income',y='Spending_Score',hue=clH.labels_,data=mall_hierarchy)